### ISSUE TITLE
is it possible to use simple_shot with CPU only?

### ISSUE THREAD

**Issue by Horace89** [mileyan/simple_shot#2]
Unfortunately on my MacBook, the evaluation command is failing:

```
python ./src/train.py -c ./configs/mini/softmax/conv4.config --evaluate --enlarge

Traceback (most recent call last):
  File "./src/train.py", line 554, in <module>
    main()
  File "./src/train.py", line 51, in main
    model = torch.nn.DataParallel(model).cuda()
  File "/Users/seb/.virtualenvs/kiss/lib/python3.7/site-packages/torch/nn/modules/module.py", line 305, in cuda
[...]
  File "/Users/seb/.virtualenvs/kiss/lib/python3.7/site-packages/torch/cuda/__init__.py", line 95, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by mileyan** [comment]
Sure. We can try to implement it.
